image: node:10.12.0

stages: 
  - build
  - test
  - deploy
heroku-deployment:
  stage: deploy
  only:
    - master
  script:
  - npm install --production
  - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/hacker-newsapp.git HEAD:refs/heads/master
